// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgfa6M7eLlL9YpcWhM_ZHUMrqulHHPmg',
    appId: '1:46671696841:web:328ce6d0ec425a6bba0e18',
    messagingSenderId: '46671696841',
    projectId: 'speedfeast-marchent',
    authDomain: 'speedfeast-marchent.firebaseapp.com',
    storageBucket: 'speedfeast-marchent.firebasestorage.app',
    measurementId: 'G-QYSQ3SMP0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PsYoo1EJqLybmUqlVJWIrz37USIvWxk',
    appId: '1:46671696841:android:68c9b8725b65158bba0e18',
    messagingSenderId: '46671696841',
    projectId: 'speedfeast-marchent',
    storageBucket: 'speedfeast-marchent.firebasestorage.app',
  );
}
